# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: PubLin
      run: dotnet publish -o publin
    - name: PubWin
      run: dotnet publish -o pubwin --os win
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
         name: linux_AMD64
         path: publin/rar_to_epub
    - name: 'Upload Artifact Win'
      uses: actions/upload-artifact@v4
      with:
         name: windows_AMD64
         path: pubwin/rar_to_epub.exe
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
